name: Build and Test FETCHTBL

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    services:
      postgres-db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          # Để PASSWD là SPACE như trong code, ta để trống password ở đây
          POSTGRES_HOST_AUTH_METHOD: trust 
          POSTGRES_DB: insurandb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gnucobol libpq-dev git make gcc autoconf libtool

      - name: Build and Install Open-COBOL-ESQL
        run: |
          git clone https://github.com/opensourcecobol/Open-COBOL-ESQL.git
          cd Open-COBOL-ESQL
          ./autogen.sh
          ./configure
          make
          sudo make install
          sudo ldconfig

      - name: Initialize Database
        run: |
        
          psql -h localhost -U postgres -d insurandb -f db/init.sql


      - name: Pre-compile with OCesql
        run: ocesql FETCHTBL.cbl FETCHTBL.cob

      - name: Prepare Libraries and Compile
        run: |
          # Copy thư viện để khớp với các Generate API của OCesql
          cp /usr/local/lib/libocesql.so ./OCESQLConnect.so
          cp /usr/local/lib/libocesql.so ./OCESQL.so
          
          # Biên dịch kèm theo đường dẫn include cho sqlca.cbl 
          cobc -x -fixed -I. FETCHTBL.cob /usr/local/lib/libocesql.so -lpq -o FETCHTBL


      - name: Pre-compile and Build FETCH-POLICY App
        run: |
          ocesql src/FETCH-POLICY.cbl src/FETCH-POLICY.cob
          cp /usr/local/lib/libocesql.so ./OCESQLConnect.so
          cp /usr/local/lib/libocesql.so ./OCESQL.so
          cobc -x -fixed -I. src/FETCH-POLICY.cob /usr/local/lib/libocesql.so -lpq -o FETCH-POLICY


      - name: Run and Verify
        env:
          LD_LIBRARY_PATH: .:/usr/local/lib:$LD_LIBRARY_PATH
          # Ép libpq kết nối tới localhost qua TCP thay vì Unix Socket
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGDATABASE: insurandb
        run: |
          # Dùng dấu | để chạy từng dòng
          echo "--- KET QUA BANG EMP (FETCHTBL) ---"
          ./FETCHTBL
          
          echo ""
          echo "--- KET QUA BANG POLICIES (FETCH-POLICY) ---"
          ./FETCH-POLICY